export default {
  topLeft: {
    message: 'Alert ! ! !',
    offset: '60px',
    duration: 100,
    position: 'top left',
    id: 'test-alert-top-left',
  },
  topLeftDark: {
    message: 'Alert ! ! !',
    theme: 'dark',
    offset: '60px',
    duration: 100,
    position: 'top left',
    id: 'test-alert-top-left-dark',
  },
  topLeftDurationZero: {
    message: 'Alert ! ! !',
    theme: 'dark',
    offset: '60px',
    duration: 0,
    position: 'top left',
    id: 'test-alert-top-left-duration-zero',
  },
  topCenter: {
    message: 'Alert ! ! !',
    offset: '60px',
    duration: 100,
    position: 'top center',
    id: 'test-alert-top-center',
  },
  topRight: {
    message: 'Alert ! ! !',
    offset: '60px',
    duration: 100,
    position: 'top right',
    id: 'test-alert-top-right',
  },
  bottomLeft: {
    message: 'Alert ! ! !',
    offset: '60px',
    duration: 100,
    position: 'bottom left',
    id: 'test-alert-bottom-left',
  },
  bottomCenter: {
    message: 'Alert ! ! !',
    offset: '60px',
    duration: 100,
    position: 'bottom center',
    id: 'test-alert-bottom-center',
  },
  bottomRight: {
    message: 'Alert ! ! !',
    offset: '60px',
    duration: 100,
    position: 'bottom right',
    id: 'test-alert-bottom-right',
  },
  badPosition: {
    message: 'Alert ! ! !',
    offset: '60px',
    duration: 100,
    position: 'bad position',
    id: 'test-alert-bad-position',
  },
};
